select
    row_number() over (order by cost_id) as cost_id,
    cast(cost_event_id as integer) as cost_event_id,
    cost_domain_id,
    cast(cost_type_concept_id as integer) as cost_type_concept_id,
    cast(currency_concept_id as integer) as currency_concept_id,
    total_charge,
    total_cost,
    total_paid,
    paid_by_payer,
    paid_by_patient,
    paid_patient_copay,
    paid_patient_coinsurance,
    paid_patient_deductible,
    paid_by_primary,
    paid_ingredient_cost,
    paid_dispensing_fee,
    payer_plan_period_id,
    amount_allowed,
    cast(revenue_code_concept_id as integer) as revenue_code_concept_id,
    revenue_code_source_value,
    cast(drg_concept_id as integer) as drg_concept_id,
    drg_source_value
from {{ ref('int_cost') }}