select 
    row_number() over (order by measurement_id) as measurement_id,
    person_id,
    cast({{ get_concept_ids(
         "measurement_source_concept_id",
         domain_id='Measurement',
         vocabulary_id=['ICD9CM', 'ICD10CM', 'CPT4', 'HCPCS'],
         vocabulary_target='SNOMED',
         required_value=0
    ) }} as varchar) as measurement_concept_id,
    measurement_date,
    measurement_datetime,
    measurement_time,
    measurement_type_concept_id,
    operator_concept_id,
    value_as_number,
    value_as_concept_id,
    unit_concept_id,
    range_low,
    range_high,
    provider_id,
    visit_occurrence_id,
    visit_detail_id,
    measurement_source_value,
    measurement_source_concept_id,
    unit_source_value,
    unit_source_concept_id,
    value_source_value,
    measurement_event_id,
    meas_event_field_concept_id
from {{ ref('int_measurement') }}