select
    d.bill_id,
    d.bill_detail_id,
    d.line_number,
    h.patient_account_number,
    d.hcpcs_line_procedure_billed,
    d.first_hcpcs_modifier_billed,
    d.second_hcpcs_modifier_billed,
    d.third_hcpcs_modifier_billed,
    d.fourth_hcpcs_modifier_billed,
    d.procedure_description,
    cast(d.total_charge_per_line as decimal) as total_charge_per_line,
    d.days_units_code,
    cast(d.days_units_billed as integer) as days_units_billed,
    d.place_of_service_line_code,
    d.first_diagnosis_pointer,
    d.second_diagnosis_pointer,
    d.third_diagnosis_pointer,
    d.fourth_diagnosis_pointer,
    d.crna_supervision_indicator,
    d.provider_agreement_line_code,
    cast(d.service_line_from_date as timestamp) as service_line_from_date,
    cast(d.service_line_to_date as timestamp) as service_line_to_date,
    d.contract_line_type_code,
    d.treatment_line_authorization,
    cast(d.total_amount_paid_per_line as decimal) as total_amount_paid_per_line,
    d.hcpcs_line_procedure_paid,
    d.first_hcpcs_modifier_paid,
    d.second_hcpcs_modifier_paid,
    d.third_hcpcs_modifier_paid,
    d.fourth_hcpcs_modifier_paid,
    d.days_units_paid,
    d.rendering_line_provider,
    cast(d.number_of_service_adjustments as integer) as number_of_service_adjustments,
    d.service_adjustment_group,
    d.service_adjustment_reason,
    cast(d.service_adjustment_amount as integer) as service_adjustment_amount,
    cast(d.service_adjustment_units as integer) as service_adjustment_units,
    d.service_adjustment_group_1,
    d.service_adjustment_reason_1,
    cast(d.service_adjustment_amount_1 as integer) as service_adjustment_amount_1,
    cast(d.service_adjustment_units_1 as integer) as service_adjustment_units_1,
    d.service_adjustment_group_2,
    d.service_adjustment_reason_2,
    cast(d.service_adjustment_amount_2 as integer) as service_adjustment_amount_2,
    cast(d.service_adjustment_units_2 as integer) as service_adjustment_units_2,
    d.service_adjustment_group_3,
    d.service_adjustment_reason_3,
    cast(d.service_adjustment_amount_3 as integer) as service_adjustment_amount_3,
    cast(d.service_adjustment_units_3 as integer) as service_adjustment_units_3,
    d.service_adjustment_group_4,
    d.service_adjustment_reason_4,
    cast(d.service_adjustment_amount_4 as integer) as service_adjustment_amount_4,
    cast(d.service_adjustment_units_4 as integer) as service_adjustment_units_4,
    h.employer_fein,
    h.facility_fein,
    h.insurer_fein,
    COALESCE(h.billing_provider_fein, h.rendering_bill_provider_fein, h.referring_provider_fein) as provider_fein,
    cast(h.total_charge_per_bill as decimal) as total_charge_per_bill,
    cast(h.total_amount_paid_per_bill as decimal) as total_amount_paid_per_bill,
    cast(h.service_bill_from_date as timestamp) as service_bill_from_date,
    cast(h.service_bill_to_date as timestamp) as service_bill_to_date,
    h.bill_type,
    h.billing_type_code,
    h.place_of_service_bill_code,
    cast(h.date_insurer_received_bill as timestamp) as date_insurer_received_bill,
    cast(h.date_of_bill as timestamp) as date_of_bill,
    cast(h.date_insurer_paid_bill as timestamp) as date_insurer_paid_bill,
    h.transaction_tracking_number
from {{ ref('stg_professional_detail') }} d
left join {{ ref('stg_professional_header') }} h
    on d.bill_id = h.bill_id