with base as (
    select
        fb.bill_id,
        det.bill_detail_id,
        det.line_number,
        det.prescription_line_number,
        ddr.ndc_billed_code,
        det.ndc_paid_code,
        det.drug_name,
        det.dispensed_as_written_code,
        det.basis_of_cost_determination,
        det.drugs_supplies_quantity,
        det.drugs_supplies_billed_amount,
        det.total_amount_paid_per_line,
        det.days_units_paid,
        det.number_of_service_adjustments,
        det.service_adjustment_group_1,
        det.service_adjustment_reason_1,
        det.service_adjustment_amount_1,
        det.service_adjustment_units_1,
        det.service_adjustment_group_2,
        det.service_adjustment_reason_2,
        det.service_adjustment_amount_2,
        det.service_adjustment_units_2,
        det.service_adjustment_group_3,
        det.service_adjustment_reason_3,
        det.service_adjustment_amount_3,
        det.service_adjustment_units_3,
        det.service_adjustment_group_4,
        det.service_adjustment_reason_4,
        det.service_adjustment_amount_4,
        det.service_adjustment_units_4,
        det.service_adjustment_group_5,
        det.service_adjustment_reason_5,
        det.service_adjustment_amount_5,
        det.service_adjustment_units_5
    from {{ ref('stg_pharmacy_detail') }} det
    left join {{ ref('fact_pharmacy_claim') }} fb
        on det.bill_id = fb.bill_id
    left join {{ ref('dim_pharmacy_drug') }} ddr
         on det.ndc_billed_code = ddr.ndc_billed_code
)

select
    bill_id,
    bill_detail_id,
    line_number,
    prescription_line_number,
    ndc_billed_code,
    ndc_paid_code,
    drug_name,
    dispensed_as_written_code,
    basis_of_cost_determination,
    drugs_supplies_quantity,
    drugs_supplies_billed_amount,
    total_amount_paid_per_line,
    days_units_paid,
    number_of_service_adjustments,
    service_adjustment_group_1,
    service_adjustment_reason_1,
    service_adjustment_amount_1,
    service_adjustment_units_1,
    service_adjustment_group_2,
    service_adjustment_reason_2,
    service_adjustment_amount_2,
    service_adjustment_units_2,
    service_adjustment_group_3,
    service_adjustment_reason_3,
    service_adjustment_amount_3,
    service_adjustment_units_3,
    service_adjustment_group_4,
    service_adjustment_reason_4,
    service_adjustment_amount_4,
    service_adjustment_units_4,
    service_adjustment_group_5,
    service_adjustment_reason_5,
    service_adjustment_amount_5,
    service_adjustment_units_5
from base