select
    d.bill_id,
    d.bill_detail_id,
    d.line_number,
    h.patient_account_number,
    cast(h.admission_date as timestamp) as admission_date,
    cast(h.discharge_date as timestamp) as discharge_date,
    h.admission_type_code,
    h.diagnosis_related_group_code,
    h.first_icd_9cm_or_icd_10cm,
    h.second_icd_9cm_or_icd_10cm,
    h.third_icd_9cm_or_icd_10cm,
    h.fourth_icd_9cm_or_icd_10cm,
    h.fifth_icd_9cm_or_icd_10cm,
    h.principal_diagnosis_code,
    h.admitting_diagnosis_code,
    h.icd_9cm_or_icd_10cm_principal,
    cast(h.principal_procedure_date as timestamp) as principal_procedure_date,
    h.first_icd_9cm_or_icd_10cm_1,
    h.second_icd_9cm_or_icd_10cm_1,
    h.third_icd_9cm_or_icd_10cm_1,
    h.fourth_icd_9cm_or_icd_10cm_1,
    cast(h.first_procedure_date as timestamp) as first_procedure_date,
    cast(h.second_procedure_date as timestamp) as second_procedure_date,
    cast(h.third_procedure_date as timestamp) as third_procedure_date,
    cast(h.fourth_procedure_date as timestamp) as fourth_procedure_date,
    d.hcpcs_line_procedure_paid,
    d.first_hcpcs_modifier_paid,
    d.second_hcpcs_modifier_paid,
    d.third_hcpcs_modifier_paid,
    d.fourth_hcpcs_modifier_paid,
    d.procedure_description,
    cast(d.total_charge_per_line as decimal) as total_charge_per_line,
    cast(d.total_amount_paid_per_line as decimal) as total_amount_paid_per_line,
    cast(d.days_units_billed as integer) as days_units_billed,
    cast(d.days_units_paid as integer) as days_units_paid,
    cast(d.service_line_from_date as timestamp) as service_line_from_date,
    cast(d.service_line_to_date as timestamp) as service_line_to_date,
    cast(h.total_charge_per_bill as decimal) as total_charge_per_bill,
    cast(h.total_amount_paid_per_bill as decimal) as total_amount_paid_per_bill,
    cast(d.number_of_service_adjustments as integer) as number_of_service_adjustments,
    d.service_adjustment_group,
    d.service_adjustment_reason,
    cast(d.service_adjustment_amount as integer) as service_adjustment_amount,
    cast(d.service_adjustment_units as integer) as service_adjustment_units,
    d.service_adjustment_group_1,
    d.service_adjustment_reason_1,
    d.service_adjustment_amount_1,
    d.service_adjustment_units_1,
    d.service_adjustment_group_2,
    d.service_adjustment_reason_2,
    cast(d.service_adjustment_amount_2 as integer) as service_adjustment_amount_2,
    cast(d.service_adjustment_units_2 as integer) as service_adjustment_units_2,
    d.service_adjustment_group_3,
    d.service_adjustment_reason_3,
    cast(d.service_adjustment_amount_3 as integer) as service_adjustment_amount_3,
    cast(d.service_adjustment_units_3 as integer) as service_adjustment_units_3,
    d.service_adjustment_group_4,
    d.service_adjustment_reason_4,
    cast(d.service_adjustment_amount_4 as integer) as service_adjustment_amount_4,
    cast(d.service_adjustment_units_4 as integer) as service_adjustment_units_4,
    h.employer_fein,
    h.facility_fein,
    h.insurer_fein,
    COALESCE(h.billing_provider_fein, h.rendering_bill_provider_fein, h.referring_provider_fein) as provider_fein,
    h.transaction_tracking_number
from {{ ref('stg_institutional_detail') }} d
left join {{ ref('stg_institutional_header') }} h 
    on d.bill_id = h.bill_id
where patient_account_number is not null