select
    d.bill_id,
    d.bill_detail_id,
    d.line_number,
    h.patient_account_number,
    cast(d.drugs_supplies_billed_amount as decimal) as drugs_supplies_billed_amount,
    cast(d.total_amount_paid_per_line as decimal) as total_amount_paid_per_line,
    d.ndc_billed_code,
    d.prescription_line_number,
    d.dispensed_as_written_code,
    d.drug_name,
    d.basis_of_cost_determination,
    cast(d.service_line_from_date as timestamp) as service_line_from_date,
    cast(d.service_line_to_date as timestamp) as service_line_to_date,
    cast(d.prescription_line_date as timestamp) as prescription_line_date,
    cast(d.drugs_supplies_quantity as integer) as drugs_supplies_quantity,
    cast(d.drugs_supplies_number_of as integer) as drugs_supplies_number_of,
    cast(d.drugs_supplies_dispensing as decimal) as drugs_supplies_dispensing,
    d.ndc_paid_code,
    cast(d.days_units_paid as integer) as days_units_paid,
    d.rendering_line_provider,
    cast(d.number_of_service_adjustments as integer) as number_of_service_adjustments,
    d.service_adjustment_group_1,
    d.service_adjustment_reason_1,
    cast(d.service_adjustment_amount_1 as integer) as service_adjustment_amount_1,
    cast(d.service_adjustment_units_1 as integer) as service_adjustment_units_1,
    d.service_adjustment_group_2,
    d.service_adjustment_reason_2,
    cast(d.service_adjustment_amount_2 as integer) as service_adjustment_amount_2,
    cast(d.service_adjustment_units_2 as integer) as service_adjustment_units_2,
    d.service_adjustment_group_3,
    d.service_adjustment_reason_3,
    cast(d.service_adjustment_amount_3 as integer) as service_adjustment_amount_3,
    cast(d.service_adjustment_units_3 as integer) as service_adjustment_units_3,
    d.service_adjustment_group_4,
    d.service_adjustment_reason_4,
    cast(d.service_adjustment_amount_4 as integer) as service_adjustment_amount_4,
    cast(d.service_adjustment_units_4 as integer) as service_adjustment_units_4,
    d.service_adjustment_group_5,
    d.service_adjustment_reason_5,
    cast(d.service_adjustment_amount_5 as integer) as service_adjustment_amount_5,
    cast(d.service_adjustment_units_5 as integer) as service_adjustment_units_5,
    cast(h.total_charge_per_bill as decimal) as total_charge_per_bill,
    cast(h.total_amount_paid_per_bill as decimal) as total_amount_paid_per_bill,
    h.bill_type,
    h.billing_type_code,
    h.employer_fein,
    h.facility_fein,
    h.insurer_fein,
    COALESCE(h.billing_provider_fein, h.rendering_bill_provider_fein, h.referring_provider_fein) as provider_fein,
    h.transaction_tracking_number,
    cast(h.bill_selection_date as timestamp) as bill_selection_date,
    cast(h.reporting_period_start_date as timestamp) as reporting_period_start_date,
    cast(h.reporting_period_end_date as timestamp) as reporting_period_end_date
from {{ ref('stg_pharmacy_detail') }} d
left join {{ ref('stg_pharmacy_header') }} h ON d.bill_id = h.bill_id